tasks:
  - init: pip install -r requirements.txt

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter

    - ms-python.debugpy

    - ms-toolsai.jupyter-keymap

    - ms-toolsai.jupyter-renderers

    - ms-toolsai.vscode-jupyter-cell-tags

    - ms-toolsai.vscode-jupyter-slideshow

ports:
  - port: 9000-9100
    onOpen: ignore
